# Generated by Django 4.1.7 on 2023-03-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnes',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=2, null=True),
        ),
    ]
