# Generated by Django 4.1.7 on 2023-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0002_personnes_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnes',
            name='date_de_naissance',
            field=models.DateField(null=True),
        ),
    ]
