# Generated by Django 4.1.7 on 2023-05-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0003_alter_personnes_date_de_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='zones',
            name='nom',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
