# Generated by Django 4.1.7 on 2023-05-28 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0004_zones_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnes',
            old_name='numero_parcelle',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='personnes',
            name='activite',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='classe',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='comprendreLire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='indexDataOcupant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='lien_parente',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='nombre_ocupant',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='situatioResidence',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personnes',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personnes',
            name='zones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Zones', to='BD_APP.zones'),
        ),
        migrations.AlterField(
            model_name='zones',
            name='agent_codificateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_codificateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zones',
            name='agent_controleur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_controleur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zones',
            name='agent_rescenseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_rescenseur', to=settings.AUTH_USER_MODEL),
        ),
    ]
