# Generated by Django 4.1.7 on 2023-05-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0005_rename_numero_parcelle_personnes_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnes',
            name='etverifie',
            field=models.BooleanField(default=False),
        ),
    ]
