# Generated by Django 4.1.7 on 2023-06-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0006_personnes_etverifie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnes',
            old_name='menage',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='personnes',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='personnes',
            name='zones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BD_APP.zones'),
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ocupant', models.CharField(max_length=100, null=True)),
                ('numero', models.CharField(max_length=100, null=True)),
                ('province', models.CharField(max_length=100, null=True)),
                ('commune', models.CharField(max_length=100, null=True)),
                ('quartier', models.CharField(max_length=100, null=True)),
                ('avenue', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=100, null=True)),
                ('zones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BD_APP.zones')),
            ],
        ),
        migrations.AddField(
            model_name='personnes',
            name='manage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BD_APP.manager'),
        ),
    ]
