# Generated by Django 4.1.7 on 2023-06-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0007_rename_menage_personnes_nombre_alter_personnes_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnes',
            old_name='manage',
            new_name='manager',
        ),
    ]
