# Generated by Django 4.1.7 on 2023-06-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0008_rename_manage_personnes_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manager',
            new_name='menager',
        ),
        migrations.RenameField(
            model_name='personnes',
            old_name='manager',
            new_name='menager',
        ),
    ]
