# Generated by Django 4.1.7 on 2023-06-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0010_rename_ville_menager_numero_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnes',
            name='numero_parcelle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
