# Generated by Django 4.1.7 on 2023-06-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0011_personnes_numero_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menager',
            name='nombre_ocupant',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menager',
            name='numero',
            field=models.IntegerField(null=True),
        ),
    ]
