# Generated by Django 4.1.7 on 2023-06-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BD_APP', '0012_alter_menager_nombre_ocupant_alter_menager_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='menager',
            name='type_menage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
